# Generated by Django 4.1.4 on 2023-01-09 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_api', '0002_customer_alter_adminuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, help_text='Specifies the amount of the payment.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='amount')),
                ('type', models.CharField(choices=[('CASHBACK', 'Cashback'), ('CHARGE', 'Charge')], default='CASHBACK', help_text='Specifies the type of the payment.', max_length=10, verbose_name='type')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='REQUESTED', help_text='Specifies the status of the payment.', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Specifies when the customer was created.', verbose_name='created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cafe_api.customer', verbose_name='customer')),
            ],
        ),
    ]
